### ISSUE TITLE
Model name 'bart-large' was not found

### ISSUE THREAD

**Issue by moussaKam** [renatoviolin/next_word_prediction#6]
When I tried to run the application I got the following error: 
```
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    import main
  File "/home/moussa/Documents/next_word_prediction/main.py", line 18, in <module>
    bart_tokenizer = BartTokenizer.from_pretrained('bart-large')
  File "/home/moussa/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 911, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/home/moussa/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 1014, in _from_pretrained
    list(cls.vocab_files_names.values()),
OSError: Model name 'bart-large' was not found in tokenizers model name list (facebook/bart-large, facebook/bart-large-mnli, facebook/bart-large-cnn, facebook/bart-large-xsum). We assumed 'bart-large' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.
```

**Comment by renatoviolin** [comment]
Do you have the latest version of transformers?
pip install -U pip
pip install -U transformers

**Comment by moussaKam** [comment]
yes I do have the latest version. 
I changed the identifier of bart from "bart-large" to "facebook/bart-large" and it worked.
